<?php
use Drupal\Core\Database\Database;
use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;
function mydata_theme() {
  return [
    'my_form' => [
      'render element' => 'form',
    ],
    
  ];
   
}
function mydata_preprocess(&$variables){
	$current_user = \Drupal::currentUser()->id();
	if ($current_user) {
		$account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
		if ($account) {
			$username = $account->get('name')->value;
			$account_array = $account->toArray();
			$roles = isset($account_array['roles'][0]['target_id']) ? $account_array['roles'][0]['target_id'] : null;
			$variables['user_name'] = $username;
			$variables['user_roles'] = $roles;
		}

		$query = \Drupal::database()->select('user__user_picture', 'n');
	    $query->addField('n', 'user_picture_target_id');
	    $query->condition('entity_id', $current_user,'=');
	    $results = $query->execute()->fetchAssoc();
		$img_id = isset($results['user_picture_target_id']) ? $results['user_picture_target_id'] : null;
		if ($img_id) {
			$file = File::load($img_id);
			if(!empty($file)){
				$url = $file->url();
			}else{
				$url = '/5ppsystem.com/web/sites/default/files/pictures/2020-02/DefaultProfile.png';
				$url_pos = strpos($url,"/sites");
				$url_valid = substr($url,$url_pos);
				$variables['user_img_url'] = $url_valid;
			}
		}
        $query1 = \Drupal::database()->select('user__field_last_name', 'ufln');
        $query1->addField('ufln', 'field_last_name_value');
        $query1->condition('entity_id', $current_user,'=');
        $results1 = $query1->execute()->fetchAssoc();
//        echo '<pre>';print_r($results1);die;
        $fname = isset($results1['field_last_name_value']) ? $results1['field_last_name_value'] : null;
        $variables['fname'] = $fname;

        $query2 = \Drupal::database()->select('user__field_state', 'ufs');
        $query2->addField('ufs', 'field_state_value');
        $query2->condition('entity_id', $current_user,'=');
        $results2 = $query2->execute()->fetchAssoc();
        $state = isset($results2['field_state_value']) ? $results2['field_state_value'] : null;
        //echo '<pre>';print_r($results2);die;
        $variables['state'] = $state;
	}
}

