<?php
use Drupal\Core\Database\Database;
use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;
function mydata_theme() {
  return [
    'my_form' => [
      'render element' => 'form',
    ],
    
  ];
   
}
function mydata_preprocess(&$variables){
	$current_user = \Drupal::currentUser()->id();
	if ($current_user) {
		$account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
		if ($account) {
			$username = $account->get('name')->value;
			$account_array = $account->toArray();
			$roles_data = $account->getRoles();
			if(in_array('parent_guardian_registering_athlete_', $roles_data) || in_array('athlete', $roles_data) ){
				$variables['role_n'] = 'Athlete';
			}else{
				$roles_data = array_flip($roles_data);
				unset($roles_data['authenticated']);
				$roles_data = array_flip($roles_data);	
				$rol_label = [];
				foreach ($roles_data  as $role ) {
						$rol_label[] = user_role_load($role)->label();
				}
				$variables['role_n']  = implode(',', $rol_label);	
			}
			//$roles = isset($account_array['roles'][0]['target_id']) ? $account_array['roles'][0]['target_id'] : null;
			$variables['user_name'] = $username;	
		}

		$query = \Drupal::database()->select('user__user_picture', 'n');
	    $query->addField('n', 'user_picture_target_id');
	    $query->condition('entity_id', $current_user,'=');
	    $results = $query->execute()->fetchAssoc();
		$img_id = isset($results['user_picture_target_id']) ? $results['user_picture_target_id'] : null;
		if ($img_id) {
			$file = File::load($img_id);
			if(!empty($file)){
				$url = $file->url();
			}else{
				$url = '/5ppsystem.com/web/sites/default/files/pictures/2020-02/DefaultProfile.png';
				$url_pos = strpos($url,"/sites");
				$url_valid = substr($url,$url_pos);
				$variables['user_img_url'] = $url_valid;
			}
		}


		//last name
        $queryl = \Drupal::database()->select('user__field_last_name', 'ufln');
        $queryl->addField('ufln', 'field_last_name_value');
        $queryl->condition('entity_id', $current_user,'=');
        $resultsl = $queryl->execute()->fetchAssoc();
        $lname = isset($resultsl['field_last_name_value']) ? $resultsl['field_last_name_value'] : null;
        $variables['lname'] = $lname;
        // first name
        $queryf = \Drupal::database()->select('user__field_first_name', 'ufln');
        $queryf->addField('ufln', 'field_first_name_value');
        $queryf->condition('entity_id', $current_user,'=');
        $resultsf = $queryf->execute()->fetchAssoc();
        $fname = isset($resultsf['field_first_name_value']) ? $resultsf['field_first_name_value'] : null;
        $variables['fname'] = $fname;
        //state
        $query2 = \Drupal::database()->select('user__field_state', 'ufs');
        $query2->addField('ufs', 'field_state_value');
        $query2->condition('entity_id', $current_user,'=');
        $results2 = $query2->execute()->fetchAssoc();
        $state = isset($results2['field_state_value']) ? $results2['field_state_value'] : null;
        $variables['state'] = $state;
	}
}

