<?php
use Drupal\Core\Database\Database;
use Drupal\file\Entity\File;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
/**
 * @file
 * Contains acme.module..
 */


/**
 * Implements hook_theme()
 * @return mixed
 */
function acme_theme() {
  $theme['hello_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL,'month_block' => NULL,'rolename' => NULL],
    'template' => 'hello',
  ];
  $theme['upcoming_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL,'month_block' => NULL],
    'template' => 'upcoming',
  ];

  $theme['faq_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'faqlist',
  ];
   $theme['bfss_manager_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'bfss_manager',
  ];

   $theme['faq_bfss_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'faq_bfss',
  ];

  $theme['payment_receipts_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'payment_receipts',
  ];
  
  $theme['athlete_profile'] = [
    'variables' => ['themeName' => NULL],
    'template' => 'athleteForm',
  ];
  $theme['athlete_form'] = [
    'variables' => ['themeName' => NULL],
    'template' => 'athForm',
  ];
  $theme['assessors_profile_dashboard_page'] = [
    'variables' => ['name' => NULL,'event_listing_block' => NULL,'private_assessment_listing_block' => NULL],
    'template' => 'assessors_profile_dashboard',
  ];
  $theme['assessment_events_page'] = [
    'variables' => ['name' => NULL,'assessment_events_block' => NULL],
    'template' => 'assessment_events',
  ];

  $theme['my_assessments_page'] = [
    'variables' => ['name' => NULL,'my_assessments_block' => NULL,'my_assessments_records_block' => NULL],
    'template' => 'my_assessments',
  ];
  $theme['term_conditions_of_funds_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'term_conditions_of_funds',
  ];
  $theme['search_athlete_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'search_athlete',
  ];
  $theme['bfss_funds_page'] = [
    'variables' => ['name' => NULL,'bfss_payment_pending_block' => NULL,'bfss_payment_paid_block' => NULL],
    'template' => 'bfss_funds',
  ];

  $theme['athletes_follow_page'] = [
    'variables' => ['name' => NULL,'athletes_follow_block' => NULL],
    'template' => 'athletes_follow',
  ];
  return $theme;
}

function acme_preprocess(&$variables){
    $current_user = \Drupal::currentUser()->id();
    $query = \Drupal::database()->select('user__user_picture', 'n');
    $query->addField('n', 'user_picture_target_id');
    $query->condition('entity_id', $current_user,'=');
    $results = $query->execute()->fetchAssoc();
    if(!empty($results)){
      $img_id = $results['user_picture_target_id'];
        $file = File::load($img_id);
        if($file != null && $file != ""){
          $url = $file->url();
          $url_pos = strpos($url,"/sites");
          $url_valid = substr($url,$url_pos);
          $variables['user_img_url'] = $url_valid;
        }else{
            $fileDefault = File::load(20);
            if($fileDefault != null && $fileDefault != ""){
                $url = $fileDefault->url();
                $url_pos = strpos($url,"/sites");
                $url_valid = substr($url,$url_pos);
                $variables['user_img_url'] = $url_valid;
            }
        }
    }    	
}

function acme_preprocess_html(&$variables) {  
  $cls = 'edit-profile-class';
    $path = \Drupal::request()->getPathInfo();
  $path_args = explode('/', $path);  
  if (count($path_args) >= 2 && !empty($path_args[3])) {
    if(strtolower($path_args[3])=="edit"){
      $variables['edit_profile_class'] = $cls;
    }
  }
}

/*

 * Hook for user login
 * Redirecting user after login
 */
function acme_user_login(\Drupal\user\UserInterface $account) {
//    echo '<pre>';print_r($account);die;
  // Default login destination to the dashboard.
    $current_user = \Drupal::currentUser()->id();
    $query = \Drupal::database()->select('mydata', 'md');
    $query->addField('md', 'popup_flag');
    $query->condition('uid', $current_user,'=');
    $results = $query->execute()->fetchAssoc();
//    echo '<pre>';print_r($current_user);
    
    if(!empty($results['popup_flag']) && $results['popup_flag'] == 'filled'){
        $current_request = \Drupal::service('request_stack')->getCurrentRequest();
        if (!$current_request->query->get('destination')) {
          $current_request->query->set(
            'destination',
            \Drupal\Core\Url::fromRoute('acme_hello')->toString()
          );
        }
    }else{
		$current_request = \Drupal::service('request_stack')->getCurrentRequest();
		//print URL::fromUserInput('/dashboard/profile')->toString();die;
		return new RedirectResponse(URL::fromUserInput('/dashboard/profile')->toString());
		
	}
}