<?php
use Drupal\Core\Database\Database;
use Drupal\file\Entity\File;
/**
 * @file
 * Contains acme.module..
 */


/**
 * Implements hook_theme()
 * @return mixed
 */
function acme_theme() {
  $theme['hello_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'hello',
  ];
  $theme['upcoming_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL],
    'template' => 'upcoming',
  ];
  $theme['athlete_profile'] = [
    'variables' => ['themeName' => NULL],
    'template' => 'athleteForm',
  ];
  $theme['athlete_form'] = [
    'variables' => ['themeName' => NULL],
    'template' => 'athForm',
  ];

  return $theme;
}

function acme_preprocess(&$variables){
$current_user = \Drupal::currentUser()->id();
    $query = \Drupal::database()->select('user__user_picture', 'n');
    $query->addField('n', 'user_picture_target_id');
    $query->condition('entity_id', $current_user,'=');
    $results = $query->execute()->fetchAssoc();
	$img_id = $results['user_picture_target_id'];
	$file = File::load($img_id);
	if($file != null && $file != ""){
	$url = $file->url();
	}
	$url_pos = strpos($url,"/sites");
	$url_valid = substr($url,$url_pos);
	$variables['user_img_url'] = $url_valid;
	// print_r($url_valid);die;
}

function acme_preprocess_html(&$variables) {  
  $cls = 'edit-profile-class';
    $path = \Drupal::request()->getPathInfo();
  $path_args = explode('/', $path);  
  if (count($path_args) >= 2 && !empty($path_args[3])) {
    if(strtolower($path_args[3])=="edit"){
      $variables['edit_profile_class'] = $cls;
    }
  }
}

/*

 * Hook for user login
 * Redirecting user after login
 */
function acme_user_login(\Drupal\user\UserInterface $account) {
//    echo '<pre>';print_r($account);die;
  // Default login destination to the dashboard.
    $current_user = \Drupal::currentUser()->id();
    $query = \Drupal::database()->select('mydata', 'md');
    $query->addField('md', 'popup_flag');
    $query->condition('uid', $current_user,'=');
    $results = $query->execute()->fetchAssoc();
//    echo '<pre>';print_r($current_user);
//    echo '<pre>';print_r($results);die;
    if(!empty($results['popup_flag']) && $results['popup_flag'] == 'filled'){
        $current_request = \Drupal::service('request_stack')->getCurrentRequest();
        if (!$current_request->query->get('destination')) {
          $current_request->query->set(
            'destination',
            \Drupal\Core\Url::fromRoute('acme_hello')->toString()
          );
        }
    }
}