<?php
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
/*
 * HOOK_theme
 */
function bfss_assessment_theme() {
return [
    'page_assessment' => [
        'variables' => [
          'data'=>[],
        ],
        'template'=>'custom/page-assessment',
    ],
    'modal_assessment' => [
        'variables' => [
          'data'=>[],
        ],
        'template'=>'custom/modal-assessment',
    ],
    'assessment_success' => [
      'variables' => [
          'message'=> null,
        ],
        'template'=>'custom/assessment-success',
    ],
    'atheltic__profile' => [
      'variables' => [
          'data'=> null,
        ],
        'template'=>'custom/atheltic--profile',
    ],
    'upcoming_group_assessments' => [
      'variables' => [
          'data'=> null,
        ],
        'template'=>'custom/upcoming-group-assessments',
    ],  
    'bfss_manager' => [
      'variables' => [
          'data'=> null,
        ],
        'template'=>'custom/bfss-manager',
    ],
    'payment_receipts' => [
      'variables' => [
          'data'=> null,
        ],
        'template'=>'custom/payment-receipts',
    ],
    'scheduled__appointments' => [
      'variables' => [
          'data'=> null,
        ],
        'template'=>'custom/scheduled--appointments',
    ],
  ];
}
/*function bfss_assessment_theme() {
  return array(
	'views_view_grid__assessments__block_1' => [
      'template' => 'views/views-view-grid--assessments--block_1',
      'base hook' => 'view',
    ],
    'views_view_grid__assessments__page_1' => [
      'template' => 'views/views-view-grid--assessments--page_1',
      'base hook' => 'view',
    ],
    'node__assessment' => [
      'template' => 'content/node--assessment',
      'base hook' => 'node',
    ],
  );
}


function bfss_assessment_entity_view_mode_alter(&$view_mode, Drupal\Core\Entity\EntityInterface $entity, $context) {
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'assessment' && $view_mode == 'full') {
    $view_mode = 'modal';      
  }
}*/


/**
 * Implements hook_user_login().
 */
function bfss_assessment_user_login($account) {
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
    if( isset($roles) && in_array('athlete', $roles) ){
      $response = new RedirectResponse("/dashboard/profile");
      $response->send();
      return;
    }
    

}