<?php
use Drupal\Core\Database\Database;
use Drupal\file\Entity\File;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
/**
 * @file
 * Contains bfss_admin.module..
 */


/**
 * Implements hook_theme()
 * @return mixed
 */
function bfss_admin_theme() {
  
  $theme['manager_assessor_account_page'] = [
    'variables' => ['name' => NULL,'manager_assessor_account_block' => NULL],
    'template' => 'manager_assessor_account',
  ];

  $theme['faqs_select_page'] = [
    'variables' => ['name' => NULL,'faqs_select_block' => NULL],
    'template' => 'faqs_select',
  ];

  $theme['add_faqs_page'] = [
    'variables' => ['name' => NULL,'add_faqs_block' => NULL,'reorder_faqs_block' => NULL],
    'template' => 'add_faqs',
  ];


  return $theme;
}