<?php
/**
 * @File
 * Example custom module for Drupal 8.
 * @author Rakesh James
 */

/**
 * Implementing hook_menu().
 */
function registration_form_menu() {
    // The paths given here need to match the ones in example.routing.yml exactly.
    $items['/registration'] = array(
        'title' => 'First page',
        'description' => 'This is a example page.',
        // The name of the route from example.routing.yml
        'route' => 'registration_form.registration',
    );
    return $items;
}

function registration_form_theme($existing, $type, $theme, $path) {
    return array(
        'registration_form' => array(
            'variables' => array(
                'test_var' => 'cha cha cha cha',
            ),
            'template' => 'registration_form',
        ),
    );
}
function registration_form_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if($form_id == 'user_login_form') {
        $form['pass']['#field_suffix'] = '<div class="pass-info">This page is protected by reCAPTCHA, and subject to the Google <a href="#">Privacy Policy</a> and <a href="#">Terms of Service</a></div>';
        $form['actions']['submit']['#value'] = 'SIGN IN';
        $form['actions']['submit']['#field_suffix'] = '<div class="forgot-password"><a href="/user/password">Forgot Password</a></div>';
    }
    if($form_id == 'user_pass') {
        $form['name']['#placeholder'] = "Enter your e-mail";

    }
}
