<?php
/**
 * @File
 * Example custom module for Drupal 8.
 * @author Rakesh James
 */

/**
 * Implementing hook_menu().
 */
function registration_form_menu() {
    // The paths given here need to match the ones in example.routing.yml exactly.
    $items['/registration'] = array(
        'title' => 'First page',
        'description' => 'This is a example page.',
        // The name of the route from example.routing.yml
        'route' => 'registration_form.registration',
    );
    return $items;
}

function registration_form_theme($existing, $type, $theme, $path) {
    return array(
        'registration_form' => array(
            'variables' => array(
                'test_var' => 'cha cha cha cha',
            ),
            'template' => 'registration_form',
        ),
    );
}