<?php
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Database\Database;
use Drupal\file\Entity\File;
/*
* Including twig template */

function edit_form_theme($existing, $type, $theme, $path) {
  	return [
	    'my_edit_form' => [
	      'render element' => 'form',
	    ],
  	];
}

// function edit_form_form_alter(&$form, $form_state, $form_id) {
// 	//print_r($form_id);
// 	//$form['actions']['submit']['#submit'][] = 'alert_message'; 
//   if($form['#form_id'] == 'user_login_form') {
//     //$form['actions']['submit']['#submit'][] = '::submitForm';
//     $form['actions']['submit']['#submit'][] = 'alert_message'; 
//   }
// }

// function alert_message(&$form, $form_state){
// 	\Drupal::logger('form_state')->notice('@type', array('@type' => print_r($form_state, 1) ));
// }