<?php
use Drupal\Core\Database\Database;
use Drupal\file\Entity\File;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
/**
 * @file
 * Contains bfss_manager.module..
 */


/**
 * Implements hook_theme()
 * @return mixed
 */
function bfss_manager_theme() {
  
  $theme['bfssmanager_profile_dashboard_page'] = [
    'variables' => ['name' => NULL,'assessments_block' => NULL,'month_block' => NULL,'rolename'=>NULL],
    'template' => 'bfssmanager_profile_dashboard',
  ];

  $theme['view_edit_active_page'] = [
    'variables' => ['name' => NULL,'view_edit_active_block' => NULL],
    'template' => 'view_edit_active',
  ];

  $theme['view_edit_deactive_page'] = [
    'variables' => ['name' => NULL,'view_edit_deactive_block' => NULL],
    'template' => 'view_edit_deactive',
  ];

  return $theme;
}